# Generated by Django 4.0.3 on 2022-04-29 14:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vaccine_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='nurse',
            name='hospital',
        ),
    ]
