# Generated by Django 4.0.3 on 2022-04-29 14:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vaccine_app', '0002_remove_nurse_hospital'),
    ]

    operations = [
        migrations.AddField(
            model_name='nurse',
            name='hospital',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='vaccine_app.hospital'),
        ),
    ]
