# Generated by Django 4.0.3 on 2022-05-10 09:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vaccine_app', '0003_nurse_hospital'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nurse',
            name='hospital',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='vaccine_app.hospital'),
        ),
    ]
